<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>getting_price_for_second_product</name>
   <tag></tag>
   <elementGuidId>a7b58068-ee49-42ce-884d-4d4d15a74adc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=&quot;add-to-cart-sauce-labs-bike-light&quot;]/ancestor::div[@class=&quot;pricebar&quot;]/div[@data-test=&quot;inventory-item-price&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
